

import java.util.Scanner;

//use class student:use constructor that reads name and gender
// and display roll number generated by system
//for 1st student rollno starts from 202301,202302...
//Enter name and gender amar male(constructor)
//your rollno is 1 name is amar and gender is male(display)
class Student
{
    private static int rollno_gen=202300;
    private int rollno;
    private String name,gender;
    Student(String name,String gender)
    {
        this.name=name;
        this.gender=gender;
        rollno_gen++;
        this.rollno=rollno_gen;
    }
    void displayStudent()
    {
        System.out.println("Rollno:"+rollno+"\tName:"+name+"\tGender:"+gender);
    }
}
public class StudentRegiStration
{
    public static void main(String args[])
    {
        Student s[]=new Student[3];//array of objects
        Scanner in=new Scanner(System.in);
        for(int i=0;i<s.length;i++)
        {
            System.out.println("Enter name,gender:");
            String n=in.nextLine();
            String g=in.nextLine();
            s[i]=new Student(n,g);
        }
        System.out.println("Entered data\n");
        for(int i=0;i<s.length;i++)
        {
            s[i].displayStudent();
        }
    }

}
